org.gradle.jvmargs=-Xmx2G

# Fabric (https://fabricmc.net/versions.html)
minecraft_version=1.21.8
yarn_mappings=1.21.8+build.1
loader_version=0.16.14

# Fabric API
fabric_version=0.130.0+1.21.8

# Mod Properties
mod_version=1.21.8_1.0.9.5
maven_group=nekiplay.meteorplus
archives_base_name=meteor-plus

# Dependency Versions

# Xaero's Mods
# Xaero's World Map (https://modrinth.com/mod/xaeros-world-map/versions)
xwm_fabric_version=1.39.13_Fabric_1.21.8
# Xaero's Minimap (https://modrinth.com/mod/xaeros-minimap/versions)
xmm_fabric_version=25.2.12_Fabric_1.21.8

# Where Is It (https://modrinth.com/mod/where-is-it-port/versions)
where_is_it_version=2.6.8+1.21.6
# YetAnotherConfigLib (https://github.com/JackFred2/WhereIsIt/blob/1.20.6/gradle.properties)
yacl_version=3.3.2+1.20.4+update.1.20.5-SNAPSHOT+update.1.20.5-SNAPSHOT

# MaLiLib (https://www.curseforge.com/minecraft/mc-mods/malilib/files/all?page=1&pageSize=20)
malilib_fileid=4946328
malilib_projectid=303119
