[versions]
mod-version = "26.1.2_1.0.9.5"

# Fabric (https://fabricmc.net/develop)
jdk = "25"
minecraft = "26.1.2"
fabric-loader = "0.19.2"
fabric-api = "0.147.0+26.1.2"

# Plugins
# Loom (https://github.com/FabricMC/fabric-loom)
loom = "1.16-SNAPSHOT"

# Meteor (https://github.com/MeteorDevelopment/meteor-client)
meteor = "26.1.2-SNAPSHOT"
baritone = "26.1-SNAPSHOT"

# Xaero's Mods
# XaeroLib
xlib = "1.1.17"
# Xaero's World Map (https://modrinth.com/mod/xaeros-world-map/versions)
xwm = "1.44.0"
# Xaero's Minimap (https://modrinth.com/mod/xaeros-minimap/versions)
xmm = "26.1.5"

# Where Is It (https://modrinth.com/mod/where-is-it-port/versions)
whereisit = "2.7.3+"
# YetAnotherConfigLib (https://github.com/ponuing/WhereIsIt/blob/26.1/gradle.properties)
yacl = "3.9.3+"

[libraries]
# Fabric base
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }

# Fabric API
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }

# Meteor Client
meteor-client = { module = "meteordevelopment:meteor-client", version.ref = "meteor" }
baritone = { module = "meteordevelopment:baritone", version.ref = "baritone" }

# Xaero's Mods
xlib = { module = "xaero.lib:xaerolib-fabric-26.1.2", version.ref = "xlib" }
xwm = { module = "xaero.map:xaeroworldmap-fabric-26.1.2", version.ref = "xwm" }
xmm = { module = "xaero.minimap:xaerominimap-fabric-26.1.2", version.ref = "xmm" }

# Where Is It
whereisit = { module = "maven.modrinth:where-is-it-port", version.ref = "whereisit" }
# YetAnotherConfigLib
yacl = { module = "maven.modrinth:yacl", version.ref = "yacl" }

[plugins]
fabric-loom = { id = "net.fabricmc.fabric-loom", version.ref = "loom" }
