[versions]
mod-version = "1.21.11_1.0.9.5"

# Fabric (https://fabricmc.net/develop)
minecraft = "1.21.11"
yarn-mappings = "1.21.11+build.6"
fabric-loader = "0.19.3"
fabric-api = "0.141.6+1.21.11"

# Plugins
# Loom (https://github.com/FabricMC/fabric-loom)
loom = "1.17-SNAPSHOT"

# Meteor (https://github.com/MeteorDevelopment/meteor-client)
meteor = "1.21.11-SNAPSHOT"
baritone = "1.21.11-SNAPSHOT"
# Starscript (https://github.com/MeteorDevelopment/starscript)
starscript = "0.2.5"
# Orbit (https://github.com/MeteorDevelopment/orbit)
orbit = "0.2.4"

# Xaero's Mods
# XaeroLib
xlib = "1.7.1"
# Xaero's World Map (https://modrinth.com/mod/xaeros-world-map/versions)
xwm = "1.44.2_Fabric_1.21.11"
# Xaero's Minimap (https://modrinth.com/mod/xaeros-minimap/versions)
xmm = "26.4.2_Fabric_1.21.11"

# Where Is It (https://modrinth.com/mod/where-is-it-port/versions)
whereisit = "2.7.5.2+1.21.11"
# YetAnotherConfigLib (https://github.com/ponuing/WhereIsIt/blob/1.21.11/gradle.properties)
yacl = "3.8.1+1.21.11-fabric"

[libraries]
# Fabric base
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
yarn = { module = "net.fabricmc:yarn", version.ref = "yarn-mappings" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }

# Fabric API
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }

# Meteor Client
meteor-client = { module = "meteordevelopment:meteor-client", version.ref = "meteor" }
baritone = { module = "meteordevelopment:baritone", version.ref = "baritone" }
starscript = { module = "org.meteordev:starscript", version.ref = "starscript" }
orbit = { module = "meteordevelopment:orbit", version.ref = "orbit" }

# Xaero's Mods
xlib = { module = "xaero.lib:xaerolib-fabric-1.21.11", version.ref = "xlib" }
xwm = { module = "xaero.map:xaeroworldmap-fabric-1.21.11", version.ref = "xwm" }
xmm = { module = "xaero.minimap:xaerominimap-fabric-1.21.11", version.ref = "xmm" }

# Where Is It
whereisit = { module = "maven.modrinth:where-is-it-port", version.ref = "whereisit" }
# YetAnotherConfigLib
yacl = { module = "dev.isxander.yacl:yet-another-config-lib-fabric", version.ref = "yacl" }

[plugins]
fabric-loom = { id = "fabric-loom", version.ref = "loom" }
