[versions]
mod-version = "1.21.11_1.0.9.5"

# Fabric (https://fabricmc.net/develop)
minecraft = "1.21.11"
fabric-loader = "0.19.2"
fabric-api = "0.141.3+1.21.11"

# Plugins
# Loom (https://github.com/FabricMC/fabric-loom)
loom = "1.16-SNAPSHOT"

# Meteor (https://github.com/MeteorDevelopment/meteor-client)
meteor = "1.21.11-SNAPSHOT"
# Starscript (https://github.com/MeteorDevelopment/starscript)
starscript = "0.2.5"
# Orbit (https://github.com/MeteorDevelopment/orbit)
orbit = "0.2.4"

# Xaero's Mods
# Xaero's World Map (https://modrinth.com/mod/xaeros-world-map/versions)
xwm = "1.40.2_Fabric_1.21.11"
# Xaero's Minimap (https://modrinth.com/mod/xaeros-minimap/versions)
xmm = "25.3.2_Fabric_1.21.11"

# Where Is It (https://modrinth.com/mod/where-is-it-port/versions)
whereisit = "2.7.4+1.21.11"
# YetAnotherConfigLib (https://github.com/ponuing/WhereIsIt/blob/1.21.11/gradle.properties)
yacl = "3.8.1+1.21.11-fabric"

# MaLiLib (https://www.curseforge.com/minecraft/mc-mods/malilib)
malilib = "7130809"

[libraries]
# Fabric base
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }

# Fabric API
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }

# Meteor Client
meteor-client = { module = "meteordevelopment:meteor-client", version.ref = "meteor" }
starscript = { module = "org.meteordev:starscript", version.ref = "starscript" }
orbit = { module = "meteordevelopment:orbit", version.ref = "orbit" }

# Xaero's Mods
xwm = { module = "maven.modrinth:xaeros-world-map", version.ref = "xwm" }
xmm = { module = "maven.modrinth:xaeros-minimap", version.ref = "xmm" }

# Where Is It
whereisit = { module = "maven.modrinth:where-is-it-port", version.ref = "whereisit" }
# YetAnotherConfigLib
yacl = { module = "dev.isxander.yacl:yet-another-config-lib-fabric", version.ref = "yacl" }

# MaLiLib
malilib = { module = "curse.maven:malilib-303119", version.ref = "malilib" }

[plugins]
fabric-loom = { id = "fabric-loom", version.ref = "loom" }
